#include "touch_sensor.h"
void init_touch_sensor_pins(void) {
	PCICR |= TOUCH_SENSORS_PCIE_MASK;
	#ifdef TOUCH_SENSORS_DDR 
	TOUCH_SENSORS_DDR &= ~TOUCH_SENSORS_PIN_MASK;
	TOUCH_SENSORS_PCMSK |= TOUCH_SENSORS_PCINT_MASK;
	#else
	LEFT_TOUCH_SENSOR_DDR &= ~LEFT_TOUCH_SENSOR_PIN_MASK;
	RIGHT_TOUCH_SENSOR_DDR &= ~RIGHT_TOUCH_SENSOR_PIN_MASK;
	LEFT_TOUCH_SENSOR_PCMSK |= (LEFT_TOUCH_SENSOR_PCINT_MASK);
	RIGHT_TOUCH_SENSOR_PCMSK |= (RIGHT_TOUCH_SENSOR_PCINT_MASK);
	#endif // TOUCH_SENSORS_DDR
}